export const uidData = [
  {
    UID: "001",
    project: "KPMC",
    letterID: "MACL5502",
    otn_sku: "KP42342",
    region: "NCR",
    language: "EN-ES-ZH",
    release_date: "7-29-2022",
    composition_date: "6-6-2022",   
    revision: "1.2",
    media: "Paper",
    printing_vendor: "Arvato",
    test_suite: "test001",
    ownergroup: "DMSS",
    client: "kpmc.client@kp.org",
    tc: "daniele.x.buccheri@kp.org",
    notes:"Lorem Ipsum is simply dummya adasd a dasd a dasd asd assd  adsds as asd sa"
      },
  {
    UID: "002",
    project: "METRS",
    letterID: "0.28",
    otn_sku: "MT45234",
    region: "SCR",
    language: "EN-ES-ZH",
    release_date: "1-2-2022",
    composition_date: "2-1-2022",  
    revision: "3.0",
    media: "Digital/Paper",
    printing_vendor: "Arvato",
    test_suite: "Test003",
    ownergroup: "DMSS",
    client: "metrs.client@kp.org",
    tc: "daniele.x.buccheri@kp.org",
    notes:"Lorem Ipsum has been the industry's standard dummy"
  },
  {
    UID: "003",
    project: "PSP",
    letterID: "PSP3242",
    otn_sku: "P76534",
    region: "NCR",
    language: "EN-ES-ZH",
    release_date: "3-9-2022",
    composition_date: "11-26-2021",  
    revision: "2.0",
    media: "Digital",
    printing_vendor: "N/A",
    test_suite: "Test005",
    ownergroup: "DMSS",
    client: "psp.client@kp.org",
    tc: "daniele.x.buccheri@kp.org",
    notes:"Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
  
  }
];